<?php
		
		require('importer/openinviter.php');
		//echo '<pre>';print_r($_REQUEST);exit;
		$inviter=new OpenInviter();
		$oi_services=$inviter->getPlugins();
		$ers ='';
		
		
		$contacts = array();
		
		 $inviter->startPlugin($_REQUEST['provider']);
		 $inviter1=$_REQUEST['provider'];
		
		if($inviter1=='yahoo')
		{
			//echo"anusha";exit;exit;
			require_once('../yahootest/classtest.php');
			// Yahoo! Account Username
			$login    = "username";
			// Yahoo! Account Password
			$password = "password";
			// Initializing Class
			$yahoo  = new GrabYahoo;
			$yahoo->service = "addressbook";
			$yahoo->isUsingProxy = false;
			// Set the Proxy Host Name, isUsingProxy is set to true
			$yahoo->proxyHost = "";
			// Set the Proxy Port Number
			$yahoo->proxyPort = "";
			// Set the location to save the Cookie Jar File
			//echo $_SERVER['DOCUMENT_ROOT'];
			$yahoo->cookieJarPath = $_SERVER['DOCUMENT_ROOT'] . "/GrabYahoo1.3";
			$yahooList = $yahoo->execService($_REQUEST['email'],$_REQUEST['password']);
			// Printing the array generated by the Class
		
			$contacts1=$yahooList;
			
			foreach($contacts1 as $keyImport=>$arrayImport) 
				{
				$name=trim((!empty($arrayImport['first_name'])?$arrayImport['first_name']:false));
				$contacts[$keyImport]=(!empty($name)?htmlspecialchars($name):$keyImport);
				}	
			// Use this line to figure out any error generated during the process
			 $ers=$yahoo->errorInfo;
			
			
		}
		else
		{
			$internal=$inviter->getInternalError();
			if ($internal) {
					$ers['inviter']=$internal;
				}	
			else if (!$inviter->login($_REQUEST['email'],$_REQUEST['password'])) {
			
					$internal=$inviter->getInternalError();
					$ers=($internal?$internal:"Login failed. Either the email provider has not responded or your login credentials are incorrect.<br>Please try again.");
				}
			else if (false===$contacts=$inviter->getMyContacts()) {
					$ers="Unable to get contacts.";
				}
		}
		//return 'ddddd';
		
		//echo 'Output';
			//	echo '<pre>';print_r($contacts);echo $ers;exit;
		

		//$this->view->error = $ers;	
		//$this->view->contacts = $contacts;
		
?>
<?php if(count($contacts)>0) { ?>

<form name="frmSend" method="post">
<table width="500" border="0" cellspacing="2" cellpadding="4" align="center">
<tr><td height="10"></td></tr>
<tr>
  <td>
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="50%" align="left">
        <table>
        	<tr>
       		 <td><input type="button" name="Submit" value="Check All" class="form_bt"  onclick="checkAll();"/></td>
             <td><input type="button" name="Submit" value="Uncheck All" class="form_bt" onclick="uncheckAll();" /></td>
            </tr>
        </table>
        </td>
        <td width="50%" align="right">
          <table>
        	<tr>
       		 <td><input type="button" name="Submit" value="Send Invites" onclick="sendInvites();" class="form_bt simplemodal-close"/></td>
             <td><input type="button" name="Submit" value="Close"  class="form_bt simplemodal-close" onclick="javascript:$.fancybox.close();" /></td>
            </tr>
        </table>
        </td>
      </tr>
      <tr><td colspan="2" height="10"></td></tr>
    </table>
  </td>
</tr>
<tr>
    <td  class="clh1">
        <table width="100%" border="0" cellspacing="0" cellpadding="0" height="20px" bordercolor="#FF0000">
          <tr>
            <td width="3%"></td>
            <td width="32%"  >
                   Name
            </td>
            <td width="65%" >E-Mail
            </td>
          </tr>
        </table>
    </td>
</tr>
<?php $i=0; foreach($contacts as $email=>$name) { ?>
<tr>
    <td>
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td width="3%">
				<input type="checkbox" value="<?php echo $email;?>" id="email_<?php echo $i;?>" name="email_<?php echo $i;?>" />
				<input type="hidden" name="hidName_<?php echo $i;?>" id="hidName_<?php echo $i;?>" value="<?php echo $name;?>" />        
            </td>
            <td align="left" width="32%">
                <?php echo $email;?>
            </td>
            <td align="left" width="65%">
                <?php echo $name;?>
            </td>
          </tr>
        </table>
    </td>
</tr>
<?php $i ++ ; } ?>
<tr>
  <td>
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr><td colspan="2" height="10"></td></tr>
      <tr>
        <td width="50%" align="left">
        <table>
        	<tr>
       		 <td><input type="button" name="Submit" value="Check All" class="form_bt"  onclick="checkAll();"/></td>
             <td><input type="button" name="Submit" value="Uncheck All" class="form_bt" onclick="uncheckAll();" /></td>
            </tr>
        </table>
        
        </td>
        <td width="50%" align="right">
         <table>
        	<tr>
       		 <td><input type="button" name="Submit" value="Send Invites" onclick="sendInvites();" class="form_bt"/></td>
             <td><input type="button" name="Submit" value="Close"  class="form_bt" onclick="javascript:$.modal.close();" /></td>
            </tr>
        </table>
        
        </td>
      </tr>
    </table>
  </td>
</tr>
<tr><td height="10"></td></tr>
</table>
</form>
<?php } else { ?>
<table width="97%" border="0" cellspacing="0" cellpadding="0" align="center">
  <tr>
    <td  height="100" style="color:#F00" valign="middle"><?php echo $ers;?></td>
  </tr>
</table>
<?php } ?>

<script>
	function checkAll() {
		var eleLen = document.frmSend.elements.length;
		for(i = 0; i < eleLen; i++) {
			if(document.frmSend.elements[i].type == 'checkbox') {
				document.frmSend.elements[i].checked = true;
			}
		}
	}
	
	function uncheckAll() {
		var eleLen = document.frmSend.elements.length;
		for(i = 0; i < eleLen; i++) {
			if(document.frmSend.elements[i].type == 'checkbox') {
				document.frmSend.elements[i].checked = false;
			}
		}
	}
	
	function sendInvites() {
		
		var eleLen = document.frmSend.elements.length;
		var emails = '';
		var names = '';
		//emails = document.getElementById('cemails').value;
		//alert(emails);
		//names = document.getElementById('frndsName').value;
		for(i = 0; i < eleLen; i++) {
		//alert(document.getElementById('email_'+i).value);
		if(document.getElementById('email_'+i)) {
			if(document.getElementById('email_'+i).type == 'checkbox' && document.getElementById('email_'+i).checked == true)    {
					emails = emails + ',' + document.getElementById('email_'+i).value;			
					//names = names + ',' + document.getElementById('hidName_'+i).value;				
				}
			 } 
		}
		//alert(emails);return false;
		if(document.getElementById('cemails').value != '') {
			document.getElementById('cemails').value = document.getElementById('cemails').value + emails;	
		} else {
			document.getElementById('cemails').value = emails.substring(1);
		}
		emails = '';
		//alert(emails);
		$.fancybox.close();
		//alert(document.getElementById('cemails').value);
		document.getElementById('cemails').readOnly = true;		
		//$.modal.close();
	}
		
</script>